# Generated by Django 6.0.7 on 2026-07-15 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_pricingplan_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingPlan',
        ),
    ]
