# Generated by Django 6.0.7 on 2026-09-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_tripcategory_itineraryitem_trip_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.CharField(choices=[('leisure', 'Vacation / Leisure'), ('cultural', 'Cultural & Sightseeing'), ('adventure', 'Adventure & Outdoor'), ('business', 'Business / Work'), ('road_trip', 'Road Trip'), ('family', 'Family Trip'), ('solo', 'Solo Travel')], default='leisure', max_length=50),
        ),
        migrations.DeleteModel(
            name='TripCategory',
        ),
    ]
