# Generated by Django 6.0.7 on 2026-09-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_flight_airline_alter_flight_arrival_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='checked',
            field=models.BooleanField(default=True),
        ),
    ]
